Array birlestime

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([3,4,5])

In [3]:
np.concatenate([x,y]) #ikiden fazla arrayi uc uca ekler

array([1, 2, 3, 3, 4, 5])

In [5]:
z = np.array([[1,2,3],
             [7,8,9]])

In [6]:
z

array([[1, 2, 3],
       [7, 8, 9]])

In [7]:
np.concatenate([z,z]) #iki boyutlu arrayi alt alta ekleme

array([[1, 2, 3],
       [7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])

In [8]:
np.concatenate([z,z], axis = 1)#iki boyutlu arrayi yan yana ekleme

array([[1, 2, 3, 1, 2, 3],
       [7, 8, 9, 7, 8, 9]])

In [9]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([7,8,9])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b

array([7, 8, 9])

In [12]:
np.vstack([a,b])#boyutları ayni olmayan arrayleri birlestirme
#vstack = vertical

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a = np.array([[99],
             [99]])

In [16]:
a

array([[99],
       [99]])

In [18]:
b = np.array([[1,2,3],
             [4,5,6]])

In [19]:
np.hstack([a,b])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])